import Link from 'next/link';
import Image from 'next/image';
import SearchBar from '../../components/SearchBar/index';
import { ChangeEvent, useState } from 'react';
import s from './currency.module.scss';
import CurrencyList from '../../components/CurrencyList';
import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';

const Currency: NextPage = ({ props }: any) => {
  const [search, setSearch] = useState<string | null>('');
  const filteredCoins = props.filter((coin) =>
    coin.name.toLowerCase().includes(search.toLowerCase())
  );

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    e.preventDefault();

    setSearch(e.target.value);
  };
  return (
    <div className="h-full">
      <Head>
        <title>Crypto App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid h-screen md:grid-rows-4 md:grid-cols-5 grid-cols-1 mx-auto px-16 py-16">
        <div className="col-start-2 text-center col-span-3 text-black font-semibold">
          <h1 className="text-4xl">
            CRYPTOCURRENCIE<span className="text-purple-700">$</span>
          </h1>
          <div
            id="search"
            className="col-start-2 h-11 mt-4 flex justify-center col-span-3 row-start-1"
          >
            <SearchBar
              type="text"
              className={s.searchbar}
              placeholder="Search..."
              onChange={handleChange}
            />
          </div>
        </div>
        <div className="row-start-2 items-start col-start-2 col-span-3">
          <CurrencyList currencies={filteredCoins} />
        </div>
      </div>
    </div>
  );
};

export default Currency;

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch(
    'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=false'
  );
  const currencies = await res.json();
  return {
    props: { props: currencies },
  };
};
